language: node_js
node_js: lts/*

global:
    # include $HOME for aws command
    - PATH=$HOME/.local/bin:$PATH
    # provide secret keys, so that awscli understands them
    - travis encrypt AWS_ACCESS_KEY_ID=$S3_KEY_ID --add
    - travis encrypt AWS_SECRET_ACCESS_KEY=$S3_KEY --add

script: npm run build && npm run test

# install awscli command line tool to sync files to s3
before_deploy: pip install --user awscli

deploy:
    on:
        all_branches: true
    skip_cleanup: true
    provider: script
    script:
        # upload all files from ./dist folder and delete files on s3 which are not in current build
        - aws s3 sync ./dist s3://gh-maps-react --delete
